#!/usr/bin/env python3
"""R4 keymap alias table: readable key name -> matrix coordinate (`r{row}c{col}`).

This is namespace ① (position) of `keymap.toml` (see `.claude/rules/40-cli-spec.md`).
Aliases anchor to the *function found in a factory-default layer0*, NOT to physical
position — so they stay correct even on the bottom row, where matrix column != physical
position (e.g. `lctrl` is at matrix r5c0 = idx125, which is physically the 5th key).

The table is generated by decoding a factory-default config's layer 0: at each occupied
matrix index the base layer holds the standard HID keycode for that physical key, so
mapping `(usage page, usage id) -> friendly alias` and pairing it with the index yields
`alias -> coordinate`. Regenerate when the layout changes:

    python tools/keymap_alias.py "/path/to/factory-default.json" -o presets/r4-keymap-aliases.json

The factory config itself is proprietary (kept local, gitignored); the *generated* table
is our own derivation of the hardware layout and is committed as the R4 preset.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

COLS, ROWS = 25, 8
_COORD_RE = re.compile(r"^r(\d+)c(\d+)$")

# --- (usage page, usage id) -> friendly alias (TOML-bare-key safe: [A-Za-z0-9_-]) ---
# Page 0x07 (keyboard/keypad)
_ALIAS_07: dict[int, str] = {0x04 + i: c for i, c in enumerate("abcdefghijklmnopqrstuvwxyz")}
_ALIAS_07.update({0x1E + i: str((i + 1) % 10) for i in range(10)})  # 1..9,0
_ALIAS_07.update({0x3A + i: f"f{i + 1}" for i in range(12)})         # f1..f12
_ALIAS_07.update({
    0x28: "enter", 0x29: "esc", 0x2A: "backspace", 0x2B: "tab", 0x2C: "space",
    0x2D: "minus", 0x2E: "equal", 0x2F: "lbracket", 0x30: "rbracket", 0x31: "backslash",
    0x33: "semicolon", 0x34: "quote", 0x35: "grave", 0x36: "comma", 0x37: "period",
    0x38: "slash", 0x39: "caps", 0x46: "printscreen", 0x47: "scrolllock", 0x48: "pause",
    0x49: "insert", 0x4A: "home", 0x4B: "pageup", 0x4C: "delete", 0x4D: "end",
    0x4E: "pagedown", 0x4F: "right", 0x50: "left", 0x51: "down", 0x52: "up",
    0x53: "numlock", 0x65: "app",
    0xE0: "lctrl", 0xE1: "lshift", 0xE2: "lalt", 0xE3: "lgui",
    0xE4: "rctrl", 0xE5: "rshift", 0xE6: "ralt", 0xE7: "rgui",
})
# Page 0x0C (consumer / media)
_ALIAS_0C: dict[int, str] = {
    0xB5: "next", 0xB6: "prev", 0xB7: "stop", 0xCD: "play", 0xE2: "mute",
    0xE9: "volup", 0xEA: "voldown", 0x70: "brightup", 0x6F: "brightdown",
}
# Page 0x92 (AM vendor) — only the factory Fn key gets a positional alias; the rest are
# undecoded vendor functions, left to coordinate/passthrough (black-box, 90 続12).
_ALIAS_92: dict[int, str] = {0x0C0B: "fn"}  # #00920C0B = Fn2 = the physical Fn key

ALIAS_NAMES: dict[tuple[int, int], str] = {
    **{(0x07, u): a for u, a in _ALIAS_07.items()},
    **{(0x0C, u): a for u, a in _ALIAS_0C.items()},
    **{(0x92, u): a for u, a in _ALIAS_92.items()},
}


def _coord(index: int) -> str:
    return f"r{index // COLS}c{index % COLS}"


def aliases_from_layer0(config: dict) -> dict[str, str]:
    """`alias -> coordinate` from a factory-default config's layer 0.

    Reads raw keycodes (NOT decoded display strings) so unassigned `#00000000` is skipped
    cleanly even though it shares the "." display glyph with the period key.
    """
    layer0 = config["key_layer"]["layer_data"][0]["layer"]
    pairs = (
        (ALIAS_NAMES.get((int(code[3:5], 16), int(code[5:9], 16))), _coord(i))
        for i, code in enumerate(layer0)
        if code != "#00000000"
    )
    table: dict[str, str] = {}
    for alias, coord in pairs:
        if alias is None:
            continue
        if alias in table:
            raise ValueError(f"duplicate alias {alias!r}: {table[alias]} and {coord}")
        table[alias] = coord
    return table


def _preset_path() -> Path:
    return Path(__file__).resolve().parent.parent / "presets" / "r4-keymap-aliases.json"


def load_preset() -> dict[str, str]:
    """The committed R4 `alias -> coordinate` preset."""
    return json.loads(_preset_path().read_text())["alias_to_coord"]


def coord_to_index(coord: str) -> int:
    """`r{row}c{col}` -> matrix index. Raises on malformed or out-of-range coords."""
    m = _COORD_RE.match(coord)
    if not m:
        raise ValueError(f"not a coordinate: {coord!r}")
    row, col = int(m.group(1)), int(m.group(2))
    if not (0 <= row < ROWS and 0 <= col < COLS):
        raise ValueError(f"coordinate out of range (row<{ROWS}, col<{COLS}): {coord!r}")
    return row * COLS + col


def resolve_position(token: str, aliases: dict[str, str] | None = None) -> int:
    """Position token (namespace ①) -> matrix index.

    Resolution order matches the spec: try the coordinate pattern `r\\d+c\\d+` first,
    then fall back to the alias table. Coordinate-first means a literal `r5c0` always
    means matrix col 0, never an alias that happens to look like one.
    """
    if _COORD_RE.match(token):
        return coord_to_index(token)
    table = load_preset() if aliases is None else aliases
    if token not in table:
        raise KeyError(f"unknown key position: {token!r} (not a coordinate or R4 alias)")
    return coord_to_index(table[token])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("config", help="factory-default config JSON to decode layer 0 from")
    ap.add_argument("-o", "--out", type=Path, default=_preset_path(),
                    help="output preset path (default: presets/r4-keymap-aliases.json)")
    args = ap.parse_args()

    table = aliases_from_layer0(json.loads(Path(args.config).read_text()))
    doc = {
        "product": "R4",
        "cols": COLS,
        "note": "alias -> matrix coordinate (index = row*25 + col). Aliases anchor to "
                "factory-default layer0 function, not physical position. Generated by "
                "tools/keymap_alias.py.",
        "count": len(table),
        "alias_to_coord": dict(sorted(table.items())),
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {len(table)} aliases -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
