#!/usr/bin/env python3
"""R4 keymap alias table: readable key name -> matrix coordinate (`r{row}c{col}`).

This is namespace ① (position) of `keymap.toml` (see `.claude/rules/40-cli-spec.md`).
Aliases anchor to the *function found in a factory-default layer0*, NOT to physical
position — so they stay correct even on the bottom row, where matrix column != physical
position (e.g. `lctrl` is at matrix r5c0 = idx125, which is physically the 5th key).

The table is generated by decoding a factory-default config's layer 0: at each occupied
matrix index the base layer holds the standard HID keycode for that physical key, so
mapping `(usage page, usage id) -> friendly alias` and pairing it with the index yields
`alias -> coordinate`. Regenerate when the layout changes:

    python tools/keymap_alias.py "/path/to/factory-default.json" -o presets/r4-keymap-aliases.json

The factory config itself is proprietary (kept local, gitignored); the *generated* table
is our own derivation of the hardware layout and is committed as the R4 preset.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from keycode import STD_NAMES

COLS, ROWS = 25, 8
_COORD_RE = re.compile(r"^r(\d+)c(\d+)$")

# Positions reuse the value vocabulary (STD_NAMES) for standard keys, so "the a key"
# (alias) and "emits a" (value) share one name. The one position-specific name: the
# physical Fn key is `fn` (its factory function is Fn2 = #00920C0B); the rest of page
# 0x92 has no positional alias and falls back to coordinate (black-box, 90 続12).
ALIAS_NAMES: dict[tuple[int, int], str] = {**STD_NAMES, (0x92, 0x0C0B): "fn"}


def _coord(index: int) -> str:
    return f"r{index // COLS}c{index % COLS}"


def aliases_from_layer0(config: dict) -> dict[str, str]:
    """`alias -> coordinate` from a factory-default config's layer 0.

    Reads raw keycodes (NOT decoded display strings) so unassigned `#00000000` is skipped
    cleanly even though it shares the "." display glyph with the period key.
    """
    layer0 = config["key_layer"]["layer_data"][0]["layer"]
    pairs = (
        (ALIAS_NAMES.get((int(code[3:5], 16), int(code[5:9], 16))), _coord(i))
        for i, code in enumerate(layer0)
        if code != "#00000000"
    )
    table: dict[str, str] = {}
    for alias, coord in pairs:
        if alias is None:
            continue
        if alias in table:
            raise ValueError(f"duplicate alias {alias!r}: {table[alias]} and {coord}")
        table[alias] = coord
    return table


def _preset_path() -> Path:
    return Path(__file__).resolve().parent.parent / "presets" / "r4-keymap-aliases.json"


def load_preset() -> dict[str, str]:
    """The committed R4 `alias -> coordinate` preset."""
    return json.loads(_preset_path().read_text())["alias_to_coord"]


def coord_to_index(coord: str) -> int:
    """`r{row}c{col}` -> matrix index. Raises on malformed or out-of-range coords."""
    m = _COORD_RE.match(coord)
    if not m:
        raise ValueError(f"not a coordinate: {coord!r}")
    row, col = int(m.group(1)), int(m.group(2))
    if not (0 <= row < ROWS and 0 <= col < COLS):
        raise ValueError(f"coordinate out of range (row<{ROWS}, col<{COLS}): {coord!r}")
    return row * COLS + col


def resolve_position(token: str, aliases: dict[str, str] | None = None) -> int:
    """Position token (namespace ①) -> matrix index.

    Resolution order matches the spec: try the coordinate pattern `r\\d+c\\d+` first,
    then fall back to the alias table. Coordinate-first means a literal `r5c0` always
    means matrix col 0, never an alias that happens to look like one.
    """
    if _COORD_RE.match(token):
        return coord_to_index(token)
    table = load_preset() if aliases is None else aliases
    if token not in table:
        raise KeyError(f"unknown key position: {token!r} (not a coordinate or R4 alias)")
    return coord_to_index(table[token])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("config", help="factory-default config JSON to decode layer 0 from")
    ap.add_argument("-o", "--out", type=Path, default=_preset_path(),
                    help="output preset path (default: presets/r4-keymap-aliases.json)")
    args = ap.parse_args()

    table = aliases_from_layer0(json.loads(Path(args.config).read_text()))
    doc = {
        "product": "R4",
        "cols": COLS,
        "note": "alias -> matrix coordinate (index = row*25 + col). Aliases anchor to "
                "factory-default layer0 function, not physical position. Generated by "
                "tools/keymap_alias.py.",
        "count": len(table),
        "alias_to_coord": dict(sorted(table.items())),
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {len(table)} aliases -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
